### ISSUE TITLE
Text Generation from CLIP-T5 Flan

### ISSUE THREAD

**Issue by reachomk** [linzhiqiu/t2v_metrics#11]
Hi, 

I wanted to generate text from CLIP-T5 Flan (i.e. ask it "generate a description of this image") and get the response in English text. How can I do this? 

I am asking because I am using VQAScore for a project, but for evaluation purposes, I need to see how CLIP-T5 Flan describes some "known" images.

**Comment by linzhiqiu** [comment]
We are working on this feature and will release it shortly after ICML (around early August). Please stay tuned!

**Comment by linzhiqiu** [comment]
@reachomk With the gracious help of @Nyandwi , we managed to support this feature now. Please refer to README for usage!

**Comment by JiahuiKChen** [comment]
I'm getting a `NotImplementedError` thrown from this [line](https://github.com/linzhiqiu/t2v_metrics/blob/main/t2v_metrics/models/vqascore_models/clip_t5/model/language_model/clip_t5.py#L71) when I try to use the CLIP-FlanT5 generate method:
```
import t2v_metrics

clip_flant5 = t2v_metrics.VQAScore(model='clip-flant5-xxl')

img_path = "images/val2017/000000380711.jpg"
prompt = "Answer the multiple choice question about the image. Only state the answer choice and nothing else. Question: is this a surfer? Choices: yes, no"
lm_answer = clip_flant5.model.generate(images=[img_path], prompts=[prompt]) 
```

I believe I'm following the README example for text generation. Any help would be appreciated, thanks!

**Comment by linzhiqiu** [comment]
> I'm getting a `NotImplementedError` thrown from this [line](https://github.com/linzhiqiu/t2v_metrics/blob/main/t2v_metrics/models/vqascore_models/clip_t5/model/language_model/clip_t5.py#L71) when I try to use the CLIP-FlanT5 generate method:
> 
> ```
> import t2v_metrics
> 
> clip_flant5 = t2v_metrics.VQAScore(model='clip-flant5-xxl')
> 
> img_path = "images/val2017/000000380711.jpg"
> prompt = "Answer the multiple choice question about the image. Only state the answer choice and nothing else. Question: is this a surfer? Choices: yes, no"
> lm_answer = clip_flant5.model.generate(images=[img_path], prompts=[prompt]) 
> ```
> 
> I believe I'm following the README example for text generation. Any help would be appreciated, thanks!

It seems huggingface recently refactor the generate() function, which causes this error.

You can use an earlier version of transformers library to fix this error:
`pip install transformers==4.36.1`

**Comment by JiahuiKChen** [comment]
This worked! Thanks
