### ISSUE TITLE
Is the code of "Improving Image Generation using VQAScore" available?

### ISSUE THREAD

**Issue by SydCS** [linzhiqiu/t2v_metrics#14]
Hi. Nice work!
I wonder if the code of "Improving Image Generation using VQAScore: VQAScore can improve text-to-image generation by selecting the highest-VQAScore images from a few (3 to 9) generated candidates." is available.
Thanks!

**Comment by linzhiqiu** [comment]
Thanks for your interest!

If you are looking for the GenAI-Bench-Rank benchmark (800 prompt with 9 images generated from SD-XL and DALL-E 3), you can refer to https://github.com/linzhiqiu/t2v_metrics/blob/main/genai_image_ranking.py
