### ISSUE TITLE
Adding new VLM?

### ISSUE THREAD

**Issue by ApocalypsezZ** [linzhiqiu/t2v_metrics#16]
Will you consider adding new multimodal LMs in the future? 

For example：InternVL-2，QWEN2-VL ( can be easily used in chinese language )

**Comment by linzhiqiu** [comment]
Yes! Our team is working on these new models and will launch an update soon in one or two weeks.

**Comment by ApocalypsezZ** [comment]
OK! Thanks again for providing such a convenient VQAscore framework that allows the effects of generating models to be further quantified!
