### ISSUE TITLE
When the prompts about GenAI-Bench for T2I generation will released? 

### ISSUE THREAD

**Issue by qingtian5** [linzhiqiu/t2v_metrics#4]
I want to know when the prompts about GenAI-Bench for T2I generation will released?  
Thanks.

**Comment by linzhiqiu** [comment]
Thanks for your interest! We will release them in the next two weeks.

**Comment by jponttuset** [comment]
Any news on the prompt set?

**Comment by linzhiqiu** [comment]
Thanks for your interest and sorry for the delay. We are busy preparing for NeurIPS and so we postpone the release of GenAI-Bench. We plan to release GenAI-Bench prompts + skill tags + human ratings altogether around early June. However, if you need GenAI-Bench early (e.g., for NeurIPS), please reach out to us at: zhiqiul@andrew.cmu.edu
