### ISSUE TITLE
ModuleNotFoundError when importing t2v_metrics

### ISSUE THREAD

**Issue by aldoz-mila** [linzhiqiu/t2v_metrics#6]
Hello, I installed the package via pip as mentioned in the readme, but I am getting the following error when importing it:

<img width="682" alt="Screenshot 2024-04-11 at 10 43 20 AM" src="https://github.com/linzhiqiu/t2v_metrics/assets/150747499/27368020-58c0-411d-a66c-d488203a8abe">

Any ideas on what is causing this? Should I instead install natively from git?

**Comment by linzhiqiu** [comment]
Thanks for spotting this bug! I fixed the pip package to resolve this ModuleNotFoundError. Please update via:
`pip install t2v_metrics==1.1`

Of course, you can always do a local pip install in case you want to later modify the t2v_metrics package. Just make sure to run the below line every time you modify the package:
`pip install -e .`

**Comment by aldoz-mila** [comment]
Wow, so fast! Thanks a lot @linzhiqiu, I installed the latest version and everything works as expected! Great work on the paper! Closing this as the issue is now solved.
