### ISSUE TITLE
Do you consider "YES", "Yes" and "yes" all as possible answers?

### ISSUE THREAD

**Issue by lijing1996** [linzhiqiu/t2v_metrics#9]
LLM does not always answer "Yes" in the template. It is better to consider all the possible "yes"s such as "YES", "Yes" and "yes".

**Comment by linzhiqiu** [comment]
This is a good point. For CLIP-FlanT5 and LLaVa1.5 we found "Yes" to work similar to (or slightly better) than "yes". We ablate a few other QA templates in the Appendix of our paper.

**Comment by lijing1996** [comment]
> This is a good point. For CLIP-FlanT5 and LLaVa1.5 we found "Yes" to work similar to (or slightly better) than "yes". We ablate a few other QA templates in the Appendix of our paper.

Yes, I also found "Yes" has a much higher possibility for CLIP-FlanT5, however it is not guaranteed for other vLLM models, for example CogVLM.

**Comment by linzhiqiu** [comment]
One thing that I found might help a little is to do an ensemble; e.g., I take P(Yes) - P(No) and found that to be a robust score across most benchmarks. For simplicity, I choose to stick to P(Yes) for CLIP-FlanT5 and LLaVA-1.5 for the current arxiv paper. It will be interesting to study how to prompt VQAScore (for different models) in the future!
